# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Personal Assistant Demo Configuration - Ollama Tool-Calling Agent
# This configuration uses tool-calling agent instead of ReAct for better reliability

general:
  use_uvloop: true
  front_end:
    _type: fastapi

functions:
  # Task Management Tools
  add_task:
    _type: personal_assistant/add_task
  list_tasks:
    _type: personal_assistant/list_tasks
  complete_task:
    _type: personal_assistant/complete_task
  delete_task:
    _type: personal_assistant/delete_task
  list_tasks_for_client:
    _type: personal_assistant/list_tasks_for_client
  add_client_task:
    _type: personal_assistant/add_client_task

  # Calculator Tools
  add_numbers:
    _type: personal_assistant/add_numbers
  subtract_numbers:
    _type: personal_assistant/subtract_numbers
  multiply_numbers:
    _type: personal_assistant/multiply_numbers
  divide_numbers:
    _type: personal_assistant/divide_numbers
  calculate_percentage:
    _type: personal_assistant/calculate_percentage

  # Date/Time Tools
  current_time:
    _type: personal_assistant/current_time
  current_date:
    _type: personal_assistant/current_date

  # Enterprise Solutions Architect Tools
  schedule_meeting:
    _type: personal_assistant/schedule_meeting
  list_meetings:
    _type: personal_assistant/list_meetings
  cancel_meeting:
    _type: personal_assistant/cancel_meeting
  add_client:
    _type: personal_assistant/add_client
  list_clients:
    _type: personal_assistant/list_clients
  add_client_note:
    _type: personal_assistant/add_client_note
  get_client_details:
    _type: personal_assistant/get_client_details
  find_client_by_name:
    _type: personal_assistant/find_client_by_name



llms:
  ollama_llm:
    _type: openai
    api_key: "ollama"
    base_url: "http://localhost:11434/v1"
    model_name: "qwen2.5:7b"
    temperature: 0.1
    max_tokens: 128
    timeout: 20
    top_p: 0.7

workflow:
  _type: tool_calling_agent
  llm_name: ollama_llm
  tool_names: [add_task, list_tasks, complete_task, delete_task, list_tasks_for_client,
               add_client_task, add_numbers, subtract_numbers, multiply_numbers, divide_numbers,
               calculate_percentage, current_time, current_date, schedule_meeting, list_meetings,
               cancel_meeting, add_client, list_clients, add_client_note, get_client_details, find_client_by_name]
  verbose: true
  max_tool_calls: 3
  recursion_limit: 10
  tool_call_timeout: 10
  max_execution_time: 30


