# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Personal Assistant Demo Configuration - Ollama Local LLM
# This configuration uses Ollama as the local LLM provider

general:
  use_uvloop: true
  front_end:
    _type: fastapi

functions:
  # Task Management Tools
  add_task:
    _type: personal_assistant/add_task
  list_tasks:
    _type: personal_assistant/list_tasks
  complete_task:
    _type: personal_assistant/complete_task
  delete_task:
    _type: personal_assistant/delete_task

  # Calculator Tools
  add_numbers:
    _type: personal_assistant/add_numbers
  subtract_numbers:
    _type: personal_assistant/subtract_numbers
  multiply_numbers:
    _type: personal_assistant/multiply_numbers
  divide_numbers:
    _type: personal_assistant/divide_numbers

  # Date/Time Tools
  current_time:
    _type: personal_assistant/current_time
  current_date:
    _type: personal_assistant/current_date

  # Enterprise Solutions Architect Tools
  schedule_meeting:
    _type: personal_assistant/schedule_meeting
  list_meetings:
    _type: personal_assistant/list_meetings
  cancel_meeting:
    _type: personal_assistant/cancel_meeting
  add_client:
    _type: personal_assistant/add_client
  list_clients:
    _type: personal_assistant/list_clients
  add_client_note:
    _type: personal_assistant/add_client_note
  get_client_details:
    _type: personal_assistant/get_client_details

  # Weather Tools (uncomment if you have OPENWEATHERMAP_API_KEY)
  # weather_info:
  #   _type: personal_assistant/weather_info
  # weather_condition:
  #   _type: personal_assistant/weather_condition

llms:
  ollama_llm:
    _type: openai
    api_key: "ollama"  # Ollama doesn't require a real API key
    base_url: "http://localhost:11434/v1"  # Ollama's default OpenAI-compatible endpoint
    model_name: "qwen2.5:7b"  # Recommended: excellent for agents, tool calling, and reasoning
    temperature: 0.1
    max_tokens: 1000

workflow:
  _type: react_agent
  tool_names: [
    add_task, list_tasks, complete_task, delete_task,
    add_numbers, subtract_numbers, multiply_numbers, divide_numbers,
    current_time, current_date,
    schedule_meeting, list_meetings, cancel_meeting,
    add_client, list_clients, add_client_note, get_client_details
    # weather_info, weather_condition  # Uncomment if using weather tools
  ]
  llm_name: ollama_llm
  verbose: true
  parse_agent_response_max_retries: 3
